apiVersion: v1
kind: Service
metadata:
  name: discovery-client
  labels:
    name: discovery-client
spec:
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
  selector:
    app: discovery-client
#  type: LoadBalancer
