apiVersion: skaffold/v2beta17
kind: Config
build:
  artifacts:
    - image: dockr.jfrog.io/mido-docker/discovery-client
      #jib: {}
      custom:
        buildCommand: mvn compile jib:build
  local: {}
deploy:
  kubectl:
    manifests:
      - k8s-*
